version: '3'
services:
  db:
    image: mysql/mysql-server:8.0.20
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '5432:5432'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./1_allow-host-ip.sql:/docker-entrypoint-initdb.d/1_allow-host-ip.sql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  mysql-data:
    driver: local
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.0.0/16